### ISSUE TITLE
Install on Windows fails - pathnames too long

### ISSUE THREAD

**Issue by dkebler** [mrjoelkemp/Dependents#113]
Just trying to help out by loading dependents on a windows 7 vm for testing purposes...but...

Installing via package control fails to bring down entire repo (without any warnings though.)
When listing via package control there is no version/package information although it exists (the directory is there but is missing folders and files)

If I clone it via git it complains about a very long file(path) name for esprima (maybe others) which is buried deep in node-modules directory.   Apparently the file structure you have chosen has exceeded window path/filename limit of 256 chars.  :-(.

another reason to disdain windows.

**Comment by mrjoelkemp** [comment]
Great catch. Thanks for reporting l.

Not sure how to fix that one if the filepath length is the problem. Will
have to investigate further this weekend.

Let me know if you come up with any ideas for a fix.

**Comment by mrjoelkemp** [comment]
Still working on this one. Trying to get vmware fusion to stop being a dick and share my network connection so I can figure out what's wrong.

**Comment by dkebler** [comment]
I just use the free vmware player.   Is that available for the mac?  no,
guess you must run fusion?

Rather than install from an iso try downloading a VM.  They are virtualbox
VM but can be run in VMware, although I have both players on my machine.
Easier to get the Vbox player for mac available
https://www.virtualbox.org/wiki/Downloads and maybe blow off fusion.
https://www.modern.ie/en-us/virtualization-tools#downloads

I think you can do more than just run IE so should be enough for  you to do
the testing you need to do.

I actually installed my VMs from ISOs I downloaded and then used a key from
a disk I had although you can run them for 30 days.
http://www.howtogeek.com/186775/how-to-download-windows-7-8-and-8.1-installation-media-legally/

Have fun.  I've spent hours learning all the ropes of running VMs :-S.
Sadly Apple has made running VMs nearly impossible but I have an older
machine around I use for that.



On Tue, Feb 24, 2015 at 10:53 AM, Joel Kemp <notifications@github.com>
wrote:

> Still working on this one. Trying to get vmware fusion to stop being a
> dick and share my network connection so I can figure out what's wrong.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrjoelkemp/sublime-dependents/issues/113#issuecomment-75820343>
> .
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by mrjoelkemp** [comment]
Thanks for the links. I'm using the modern.ie vms and getting network
troubles. Will figure it out. If all else fails, i have a mac mini with a
Windows vm lying around with dust somewhere.

Fun times.

**Comment by mrjoelkemp** [comment]
This is a much larger issue: 

* https://github.com/joyent/node/issues/6960
* https://github.com/npm/npm/issues/3697

Not much I can do here. It might work on windows assuming that the files that have paths that are too long aren't useful (like tests).

I'll confirm that the plugin is usable on windows once #124 is fixed.

**Comment by dkebler** [comment]
recent pull of package to my windows VM confirms it won't work.  So looks like something in those long paths is apparently critical.

**Comment by mrjoelkemp** [comment]
Not even virtual drive mapping seems possible since this would have to happen before the package in installed: http://support.code42.com/CrashPlan/Latest/Troubleshooting/Windows_File_Paths_Longer_Than_255_Characters.

I think https://docs.npmjs.com/cli/dedupe is the only possible solution to this. I used it (without specifying a particular package) and removed a ton of code within node_modules, but I could maybe dedupe more aggressively. Will try that to see if it's successful.

**Comment by dkebler** [comment]
I will try these to identify the culprits
http://stackoverflow.com/questions/12697259/how-do-i-find-files-with-a-path-length-greater-than-260-characters-in-windows
http://pathlengthchecker.codeplex.com/

if there a just a few maybe we can manually change them?

As I read around this this has been an endemic problem with node_modules
for awhile :-(.

Read through your contributors page and what I scratch my head at is how
the js code is interpreted.  I mean st2/3 contains an embedded python
interpretor (so that one doesn't have to install python externally).   How
does that work for js code?  I assume one of those node-modules a js
interpretor?   Or does one need node.js installed for your plugin to work?

So my thought...For end use (as opposed to development) is there any reason
to have all the complete node-module folders?  If not can a production
script pull out the dependent js files and group them together and make any
changes to calling code?  In which case you could put up two repos.  A
production repo for any os and another for those wanting to contribute, a
dev repo, which could only be used in osx/linux?

What a pain well first I can determine the extent of the issue.




On Sat, Mar 14, 2015 at 5:25 PM, Joel Kemp <notifications@github.com> wrote:

> Reopened #113 <https://github.com/mrjoelkemp/Dependents/issues/113>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrjoelkemp/Dependents/issues/113#event-254105419>.
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by mrjoelkemp** [comment]
Yeah, folks wanting to use JS features need node.js installed. If that's
not stated in the docs, then feel free to stress it. If users don't have it
installed, then they see an error dialog stating that node couldn't be
found.

The npm dedupe does the folder reorganization that you hinted at. If I
could achieve a truly flat directory structure, then the problem goes away.

Most folks write js plugins and in inline the one or two necessary js
files. Dependents depends on too many external npm modules to do that.

There might be some crazy solution possible using Browserify to create a
single bundle of all dependencies. That's not trivial though.

Sass folks also need nodejs installed, btw. At least for the Dependents
feature.

If you could track down the offending directories, that would be a huge
win.

**Comment by dkebler** [comment]
I already has nodejs installed so I didn't notice the dependency.

Since the package is (will be) used beyond just js coders then yes that
needs to be stated up front.  I just happened to be using npm for some of
my web stuff otherwise I didn't have any need for nodejs.

YEA Just now got dependents working in windows.....well in part.

Loaded nodejs in windows (reboot for updating path...argh).   Cloned repo
into c: root.  Made a symbolic link to packages directory (the complete
sublime package path is like 65+ chars in windows!).  It works.  Well at
least jump to dependency works.  Find dependents unfortunately says can't
find despite a few different permutations of .deprc.   i.e.  /, \,
nothing.  I suspect the ole / vs windows \ may be the problem.

So some success.
-----------

Using found .deprc
Executing:  node C:\Users\david\AppData\Roaming\Sublime Text
3\Packages\dependents\node_modules/dependents/bin/dependents.js
--directory=C:\Users\david\Desktop\dependents\tests\scss
C:\Users\david\Desktop\dependents\tests\scss\base\_base-theme.scss
Dependents: Fetch time: 0.3540349006652832
Dependents: 0 dependents found:

error: Dependents

Can't find any file that depends on this file
Run_Dependents {'etime': '0.4', '_filename': 'Dependents.py'}

-------------

To track down long path culprits I did this.  Loaded a copy repo right in
the root of C drive.  Ran the length program using 160 as a minimum (about
60 char for the user path to dependents folder in windows sublime
install!).  Sorted them.  Anything above 190 is clearly a problem above 180
maybe.  By putting repo in root C I am sure that none got truncated (not
cloned) as 226 was longest.

attached is csv file



On Sun, Mar 15, 2015 at 12:41 PM, Joel Kemp <notifications@github.com>
wrote:

> Yeah, folks wanting to use JS features need node.js installed. If that's
> not stated in the docs, then feel free to stress it. If users don't have it
> installed, then they see an error dialog stating that node couldn't be
> found.
>
> The npm dedupe does the folder reorganization that you hinted at. If I
> could achieve a truly flat directory structure, then the problem goes away.
>
> Most folks write js plugins and in inline the one or two necessary js
> files. Dependents depends on too many external npm modules to do that.
>
> There might be some crazy solution possible using Browserify to create a
> single bundle of all dependencies. That's not trivial though.
>
> Sass folks also need nodejs installed, btw. At least for the Dependents
> feature.
>
> If you could track down the offending directories, that would be a huge
> win.
>
> On Mar 15, 2015 2:20 PM, "dkebler" <notifications@github.com> wrote:
>
> > I will try these to identify the culprits
> >
> >
> http://stackoverflow.com/questions/12697259/how-do-i-find-files-with-a-path-length-greater-than-260-characters-in-windows
> > http://pathlengthchecker.codeplex.com/
> >
> > if there a just a few maybe we can manually change them?
> >
> > As I read around this this has been an endemic problem with node_modules
> > for awhile :-(.
> >
> > Read through your contributors page and what I scratch my head at is how
> > the js code is interpreted. I mean st2/3 contains an embedded python
> > interpretor (so that one doesn't have to install python externally). How
> > does that work for js code? I assume one of those node-modules a js
> > interpretor? Or does one need node.js installed for your plugin to work?
> >
> > So my thought...For end use (as opposed to development) is there any
> reason
> > to have all the complete node-module folders? If not can a production
> > script pull out the dependent js files and group them together and make
> any
> > changes to calling code? In which case you could put up two repos. A
> > production repo for any os and another for those wanting to contribute, a
> > dev repo, which could only be used in osx/linux?
> >
> > What a pain well first I can determine the extent of the issue.
> >
> >
> >
> >
> > On Sat, Mar 14, 2015 at 5:25 PM, Joel Kemp <notifications@github.com>
> > wrote:
> >
> > > Reopened #113 <https://github.com/mrjoelkemp/Dependents/issues/113>.
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/mrjoelkemp/Dependents/issues/113#event-254105419>.
> > >
> >
> >
> >
> > --
> > Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
> > David
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/mrjoelkemp/Dependents/issues/113#issuecomment-81187583>
>
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrjoelkemp/Dependents/issues/113#issuecomment-81212702>
> .
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by dkebler** [comment]
take back the last "in part"   Checked out my latest branch, and opened a
clean version of my test folder in sublime and find dependents works
great!

All the is good.   Even new key and mouse bindings work!

So for now we have a work around for windows users (.git clone into root
and symlink) which I can write into documentation.
Will do that and also document the nodejs dependency.   I think you should
take out the node_path setting all together and we can just say that nodejs
MUST be in your environment path regardless the OS.  That's not an issue
for linux nor windows as node JS loads into a typically pathed directory in
Linux and in windows the install adds the nodejs directory to the path
variable.

Been a good waste of a wet Sunday :-).

On Sun, Mar 15, 2015 at 2:58 PM, David Kebler <d@kebler.net> wrote:

> I already has nodejs installed so I didn't notice the dependency.
>
> Since the package is (will be) used beyond just js coders then yes that
> needs to be stated up front.  I just happened to be using npm for some of
> my web stuff otherwise I didn't have any need for nodejs.
>
> YEA Just now got dependents working in windows.....well in part.
>
> Loaded nodejs in windows (reboot for updating path...argh).   Cloned repo
> into c: root.  Made a symbolic link to packages directory (the complete
> sublime package path is like 65+ chars in windows!).  It works.  Well at
> least jump to dependency works.  Find dependents unfortunately says can't
> find despite a few different permutations of .deprc.   i.e.  /, \,
> nothing.  I suspect the ole / vs windows \ may be the problem.
>
> So some success.
> -----------
>
> Using found .deprc
> Executing:  node C:\Users\david\AppData\Roaming\Sublime Text
> 3\Packages\dependents\node_modules/dependents/bin/dependents.js
> --directory=C:\Users\david\Desktop\dependents\tests\scss
> C:\Users\david\Desktop\dependents\tests\scss\base\_base-theme.scss
> Dependents: Fetch time: 0.3540349006652832
> Dependents: 0 dependents found:
>
> error: Dependents
>
> Can't find any file that depends on this file
> Run_Dependents {'etime': '0.4', '_filename': 'Dependents.py'}
>
> -------------
>
> To track down long path culprits I did this.  Loaded a copy repo right in
> the root of C drive.  Ran the length program using 160 as a minimum (about
> 60 char for the user path to dependents folder in windows sublime
> install!).  Sorted them.  Anything above 190 is clearly a problem above 180
> maybe.  By putting repo in root C I am sure that none got truncated (not
> cloned) as 226 was longest.
>
> attached is csv file
>
>
>
> On Sun, Mar 15, 2015 at 12:41 PM, Joel Kemp <notifications@github.com>
> wrote:
>
>> Yeah, folks wanting to use JS features need node.js installed. If that's
>> not stated in the docs, then feel free to stress it. If users don't have
>> it
>> installed, then they see an error dialog stating that node couldn't be
>> found.
>>
>> The npm dedupe does the folder reorganization that you hinted at. If I
>> could achieve a truly flat directory structure, then the problem goes
>> away.
>>
>> Most folks write js plugins and in inline the one or two necessary js
>> files. Dependents depends on too many external npm modules to do that.
>>
>> There might be some crazy solution possible using Browserify to create a
>> single bundle of all dependencies. That's not trivial though.
>>
>> Sass folks also need nodejs installed, btw. At least for the Dependents
>> feature.
>>
>> If you could track down the offending directories, that would be a huge
>> win.
>>
>> On Mar 15, 2015 2:20 PM, "dkebler" <notifications@github.com> wrote:
>>
>> > I will try these to identify the culprits
>> >
>> >
>> http://stackoverflow.com/questions/12697259/how-do-i-find-files-with-a-path-length-greater-than-260-characters-in-windows
>> > http://pathlengthchecker.codeplex.com/
>> >
>> > if there a just a few maybe we can manually change them?
>> >
>> > As I read around this this has been an endemic problem with node_modules
>> > for awhile :-(.
>> >
>> > Read through your contributors page and what I scratch my head at is how
>> > the js code is interpreted. I mean st2/3 contains an embedded python
>> > interpretor (so that one doesn't have to install python externally). How
>> > does that work for js code? I assume one of those node-modules a js
>> > interpretor? Or does one need node.js installed for your plugin to work?
>> >
>> > So my thought...For end use (as opposed to development) is there any
>> reason
>> > to have all the complete node-module folders? If not can a production
>> > script pull out the dependent js files and group them together and make
>> any
>> > changes to calling code? In which case you could put up two repos. A
>> > production repo for any os and another for those wanting to contribute,
>> a
>> > dev repo, which could only be used in osx/linux?
>> >
>> > What a pain well first I can determine the extent of the issue.
>> >
>> >
>> >
>> >
>> > On Sat, Mar 14, 2015 at 5:25 PM, Joel Kemp <notifications@github.com>
>> > wrote:
>> >
>> > > Reopened #113 <https://github.com/mrjoelkemp/Dependents/issues/113>.
>> > >
>> > > —
>> > > Reply to this email directly or view it on GitHub
>> > > <https://github.com/mrjoelkemp/Dependents/issues/113#event-254105419
>> >.
>> > >
>> >
>> >
>> >
>> > --
>> > Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
>> > David
>> >
>> > —
>> > Reply to this email directly or view it on GitHub
>> > <
>> https://github.com/mrjoelkemp/Dependents/issues/113#issuecomment-81187583
>> >
>>
>> > .
>> >
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mrjoelkemp/Dependents/issues/113#issuecomment-81212702>
>> .
>>
>
>
>
> --
> Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
> David
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by mrjoelkemp** [comment]
Great work @dkebler! Glad to hear it's working well. Windows users will definitely benefit from your time spent :)

The `node_path` option came from https://github.com/mrjoelkemp/Dependents/issues/93, and keeping the option doesn't hurt for similar cases.

Will get to merging your other PR soon. Would you like to add the doc changes from this issue into the existing PR?

**Comment by dkebler** [comment]
yes let me add that before you merge.    Point of clarity
then....`node_path` is really a general not a js specific setting right?

On Sun, Mar 15, 2015 at 4:02 PM, Joel Kemp <notifications@github.com> wrote:

> Great work @dkebler <https://github.com/dkebler>! Glad to hear it's
> working well. Windows users will definitely benefit from your time spent :)
>
> The node_path option came from #93
> <https://github.com/mrjoelkemp/Dependents/issues/93>, and keeping the
> option doesn't hurt for similar cases.
>
> Will get to merging your other PR soon. Would you like to add the doc
> changes from this issue into the existing PR?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrjoelkemp/Dependents/issues/113#issuecomment-81282399>
> .
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by mrjoelkemp** [comment]
Yes, `node_path` is a necessary configuration for all features if the default node path does not suffice.

**Comment by mrjoelkemp** [comment]
Landed the documentation based solution via #131.

**Comment by mrjoelkemp** [comment]
Rejoice npm3: https://github.com/npm/npm/issues/3697#issuecomment-114665926.

I'll be using this soon.

**Comment by dkebler** [comment]
All rejoice!

well maybe after all the dust settles from npm3 deprecations and broken
packages.  All the warnings I get lately saying such and such will be
deprecated, blah blah with 3 indicate things might be messy for bit :-).

On Fri, Jun 26, 2015 at 8:13 PM, Joel Kemp <notifications@github.com> wrote:

> Rejoice npm3: npm/npm#3697 (comment)
> <https://github.com/npm/npm/issues/3697#issuecomment-114665926>.
>
> I'll be using this soon.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrjoelkemp/Dependents/issues/113#issuecomment-115948240>
> .
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by mrjoelkemp** [comment]
Just released 3.0.0 of Dependents which used dedupe successfully to flatten the dependency list! Unless one of the node tools is using a really deep and unique set of dependencies, Windows users should be able to use dependents successfully.

As you can tell from the [number of deletions](https://github.com/mrjoelkemp/Dependents/pull/177), there's a good chance that this works. There's also a good chance that I broke something. Any confirmation of this plugin working on Windows would be super awesome and appreciated.

**Comment by dkebler** [comment]
Sure I will run 3.0.0 in my windows vm and report back.

On Thu, Jul 23, 2015 at 9:29 PM, Joel Kemp <notifications@github.com> wrote:

> Just released 3.0.0 of Dependents which used dedupe successfully to
> flatten the dependency list! Unless one of the node tools is using a really
> deep and unique set of dependencies, Windows users should be able to use
> dependents successfully.
>
> As you can tell from the number of deletions
> <https://github.com/mrjoelkemp/Dependents/pull/177>, there's a good
> chance that this works. There's also a good chance that I broke something.
> Any confirmation of this plugin working on Windows would be super awesome
> and appreciated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrjoelkemp/Dependents/issues/113#issuecomment-124325480>
> .
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by mrjoelkemp** [comment]
Thanks!

**Comment by dkebler** [comment]
Report:  Works without error in Windows from a clean install from
packagecontrol.  from here C:\Users\david\AppData\Roaming\Sublime Text
3\Packages\Dependents

Looks like dedupe (npm3) did the trick and looks like you have updated the
readme file already to reflect this so its all good to go.   I'd remove the
alternate install instructions and apology.   It's unlikely their username
in the path would be much longer than mine "david" so I don't see the the
issue of the 256 limit cropping up for specific installs.

On Fri, Jul 24, 2015 at 2:11 PM, David Kebler <d@kebler.net> wrote:

> Sure I will run 3.0.0 in my windows vm and report back.
>
> On Thu, Jul 23, 2015 at 9:29 PM, Joel Kemp <notifications@github.com>
> wrote:
>
>> Just released 3.0.0 of Dependents which used dedupe successfully to
>> flatten the dependency list! Unless one of the node tools is using a really
>> deep and unique set of dependencies, Windows users should be able to use
>> dependents successfully.
>>
>> As you can tell from the number of deletions
>> <https://github.com/mrjoelkemp/Dependents/pull/177>, there's a good
>> chance that this works. There's also a good chance that I broke something.
>> Any confirmation of this plugin working on Windows would be super awesome
>> and appreciated.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/mrjoelkemp/Dependents/issues/113#issuecomment-124325480>
>> .
>>
>
>
>
> --
> Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
> David
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by mrjoelkemp** [comment]
WOOOOOOOOHOOOOOOOOOO!!!!!!!!!! :)

Thanks for confirming. That's great news.
