### ISSUE TITLE
Stylus Support

### ISSUE THREAD

**Issue by dkebler** [mrjoelkemp/Dependents#139]
How about css preprocessor Stylus support?  https://learnboost.github.io/stylus/

It seems to be the up and coming player and the syntax is mostly the same SASS.  Been considering using it if I can rewrite a couple bower packages I use.    http://sass2stylus.com/

It uses @import just without the closing ; so maybe current parsing will work unmodified.
https://learnboost.github.io/stylus/docs/import.html
Then just need to recognize the new file extension .styl   

Thus for not too much work Dependents could support another css preprocessor?

**Comment by mrjoelkemp** [comment]
Definitely open to it. Does Stylus support the same import semantics as Sass (i.e., does it lookup imports the same way)? 

Have a sample Stylus project that I could use as a reference when testing?

**Comment by dkebler** [comment]
I could make up something like I did for sass.   As far I as I know the
@import is used in the same way.  It does also support @require which that
link I gave explains the difference.

No rush on this so might as well table it until I have some testing sample
which might be a bit.  Just thought this might be a relatively easy
inclusion.

On Sat, Jun 27, 2015 at 11:04 AM, Joel Kemp <notifications@github.com>
wrote:

> Definitely open to it. Does Stylus support the same import semantics as
> Sass (i.e., does it lookup imports the same way)?
>
> Have a sample Stylus project that I could use as a reference when testing?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrjoelkemp/Dependents/issues/139#issuecomment-116110230>
> .
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by mrjoelkemp** [comment]
Thanks. No worries about the test cases. I'll make it happen. Been getting
requests for LESS support as well.

**Comment by dkebler** [comment]
FYI,

not sure you have already supported .sass syntax(files) but probably should
although .scss seems the standard

So the cases are for @import

.sass
@import name
.scss
@import 'name'';
.styl   (stylus)
@import 'bar'

Also " or ' are allowed.

So maybe the way you currently parse @import
to get the filename would work for all?

Of course one could add the extension to any of those so parsing should
ignore that unless of course its deliberate like importing some plain css
file  'name.css'

Reading more carefully about stylus
*@import* also supports index styles. This means when you @import blueprint,
it will resolve *either* blueprint.styl *or* blueprint/index.styl
so 'name' in my example might refer to a diretory...yuck.

Futher stylus has globbing which means that

@import 'product/*'

This would import all the stylus sheets from the product directory in such
structure:

-------

here is the LESS import documentation.  Not really different except for the
"directives" which may have no bearing on Dependents save for maybe the two
directives less and css.

http://lesscss.org/features/#import-options

--------

Well then maybe its best to have a test set that addresses all these so
that we can know for sure Dependents is going to work correctly in all
cases.

**Comment by mrjoelkemp** [comment]
Sooo close: https://github.com/mrjoelkemp/Dependents/pull/142

It was actually a fair bit of work to get this in:

1. Had to create detective-stylus to find dependencies: https://github.com/mrjoelkemp/node-detective-stylus
1. Had to recreate the stylus lookup algorithm: https://github.com/mrjoelkemp/node-stylus-lookup
 - Note that it doesn't yet support globbing and additional paths
1. Had to (still have to actually) wire up the use of the aforementioned tools in node-dependents for the Find Dependents feature
1. Had to support a `styles_root` setting since using `sass_root` didn't make sense

Almost there! I was eager to see how much work would be necessary to support a new language, so this was a good exercise to see the pain points.

**Comment by mrjoelkemp** [comment]
Done. @dkebler mind pulling down the latest master and seeing if stylus support works and whether or not the new `styles_root` breaks your setup (for backCompat, it should use `sass_root` if `styles_root` isn't defined)?

**Comment by dkebler** [comment]
Made a tests/styles directory identical to the scss.  It preprocesses fine
but Dependents throws errors.   Should work if you open a new window at
tests level or tests/styles level as I have .deprc set for both cases.

BTW Style does NOT use the underscore implicitly for partials.  If you use
in the the filename it MUST appear the @import path.   This is different
from scss which I discovered when trying to compile it.  In a way this is
simplier for you but as I say not identical to the code you had for scss
which checks for _name.scss  if it doesn't find "name.scss"

I threw in a glob in the Stylus code for testing.  Dependents will have to
load all three files in this case.

I pushed up to my github and did a PR so you can have the new tests/styles
directory.

BTW npm has a Stylus package for making sure code you are testing with
Dependents is actually valid stylus code which I did.


=====below is console output for jump to dependency.


error: Dependents

Please set the "root" setting in your .deprc file

For more info visit: https://github.com/mrjoelkemp/Dependents
error: Dependents

Setup was not successful. Please file an issue

For more info visit: https://github.com/mrjoelkemp/Dependents
JumpToDependency: region (329, 336)
JumpToDependency: line (320, 347)
JumpToDependency: strings on line ['vendors/_packages']
JumpToDependency: regions [(329, 346)]
JumpToDependency: Extracted Path {'path': 'vendors/_packages'}
JumpToDependency: Extension found in dependency name
Exception in thread Thread-360:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File
"/home/david/.config/sublime-text-3/Packages/Dependents/JumpToDependency.py",
line 84, in run
    'directory': self.window.styles_root,
AttributeError: 'Window' object has no attribute 'styles_root'

On Mon, Jun 29, 2015 at 12:37 PM, Joel Kemp <notifications@github.com>
wrote:

> Done. @dkebler <https://github.com/dkebler> mind pulling down the latest
> master and seeing if stylus support works and whether or not the new
> styles_root breaks your setup (for backCompat, it should use sass_root if
> styles_root isn't defined)?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mrjoelkemp/Dependents/issues/139#issuecomment-116812103>
> .
>



-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by mrjoelkemp** [comment]
> Made a tests/styles directory identical to the scss.  It preprocesses fine but Dependents throws errors.

It might be related to my comments on the PR regarding the setting being `style_root`. From my tests outside of the Dependents' test directory, everything seemed to work fine. I'll verify once I merge your PR.

> Should work if you open a new window at tests level or tests/styles level as I have .deprc set for both cases.

I shipped a fix that allows Dependents to respect .deprc files within subdirectories. You should be able to use the plugin fine without opening a separate window pointing to the tests directory.

> BTW Style does NOT use the underscore implicitly for partials.

Yeah, I looked into the differences in order to implement the stylus lookup algorithm. Thanks for the heads up though. I have test cases for what types of lookups I currently support: https://github.com/mrjoelkemp/node-stylus-lookup/blob/master/test/test.js#L27-L58.

> I threw in a glob in the Stylus code for testing.  Dependents will have to
load all three files in this case.

This would be really cool for JumpToDependency to support, but it's a departure from the behavior of every other module type. I'd look into this if there's a lot of interest.

> I pushed up to my github and did a PR so you can have the new tests/styles
directory. BTW npm has a Stylus package for making sure code you are testing with
Dependents is actually valid stylus code which I did.

Thanks a ton. Appreciate the help.

**Comment by dkebler** [comment]
FYI,

I am messing around with a new webapp template that uses  sass "indent"
syntax (as opposed to scss) and Dependents fails

That being with no quotes and no following ;.   If I put them in then no
problem, without and it can't parse it correctly.

@import base/topography

Looks like it found the file name but missed the leading path  base/

```
find_base_path: Closest folder with a deprc:
/mnt/AllData/hacking/testing/gulp2-starter/app/assets/stylesheets
find_base_path: Closest folder with a deprc:
/mnt/AllData/hacking/testing/gulp2-starter/app/assets/stylesheets
project_settings: Using found .deprc within:
/mnt/AllData/hacking/testing/gulp2-starter/app/assets/stylesheets/.deprc
project_settings: Using found .deprc within:
/mnt/AllData/hacking/testing/gulp2-starter/app/assets/stylesheets/.deprc
project_settings: setting sass_root for backCompat ./
project_settings: Using these settings:  {'node_path': '', 'sass_root':
'./', 'styles_root': './', 'root': '', 'config': '', 'exclude': [],
'build_config': ''}
command_setup: Relative sass_root set to
/mnt/AllData/hacking/testing/gulp2-starter/app/assets/stylesheets
JumpToDependency: region (77, 87)
JumpToDependency: line (64, 87)
JumpToDependency: strings on line []
JumpToDependency: No strings found using word region: typography
JumpToDependency: Extracted Path {'path': 'typography'}
JumpToDependency: Extension found in dependency name
JumpToDependency: Sass lookup for: typography.sass
Executing:  node
/home/david/.config/sublime-text-3/Packages/Dependents/node_modules/sass-lookup/bin/cli.js
--filename=/mnt/AllData/hacking/testing/gulp2-starter/app/assets/stylesheets/global.sass
--directory=./ typography.sass
BaseThread: Opening: /opt/sublime_text/typography.sass
Missing file {'_filename': 'BaseThread.py', 'filename':
'/opt/sublime_text/typography.sass'}
error: Dependents
```


well then one if the cases you were thinking about?










--------------

On Sat, Jun 27, 2015 at 1:44 PM, David Kebler <d@kebler.net> wrote:

> FYI,
>
> not sure you have already supported .sass syntax(files) but probably
> should although .scss seems the standard
>
> So the cases are for @import
>
> .sass
> @import name
> .scss
> @import 'name'';
> .styl   (stylus)
> @import 'bar'
>
> Also " or ' are allowed.
>
> So maybe the way you currently parse @import
> to get the filename would work for all?
>
> Of course one could add the extension to any of those so parsing should
> ignore that unless of course its deliberate like importing some plain css
> file  'name.css'
>
> Reading more carefully about stylus
> *@import* also supports index styles. This means when you @import
> blueprint, it will resolve *either* blueprint.styl *or*
> blueprint/index.styl
> so 'name' in my example might refer to a diretory...yuck.
>
> Futher stylus has globbing which means that
>
> @import 'product/*'
>
> This would import all the stylus sheets from the product directory in
> such structure:
>
> -------
>
> here is the LESS import documentation.  Not really different except for
> the "directives" which may have no bearing on Dependents save for maybe the
> two directives less and css.
>
> http://lesscss.org/features/#import-options
>
> --------
>
> Well then maybe its best to have a test set that addresses all these so
> that we can know for sure Dependents is going to work correctly in all
> cases.
>
>
>
>
>


-- 
Cheers, Cuidate, TTFN <http://www.youtube.com/watch?v=5Gu50vq5ux4>
David

**Comment by mrjoelkemp** [comment]
Good catch. Filing a separate issue for sass.
