### ISSUE TITLE
Setup error

### ISSUE THREAD

**Issue by mrjoelkemp** [mrjoelkemp/Dependents#151]
Reported by @mateodelnorte. 

```
Dependents

Setup was not successful. Please file an issue

For more info visit: https://github.com/mrjoelkemp/Dependents

Here's the console info: 

Package Control: No updated packages
Indexing gherkin phrases done
find_base_path: Closest folder with a deprc: /Users/mattwalters/development/electronifie/denormalizer
find_base_path: Closest folder with a deprc: /Users/mattwalters/development/electronifie/denormalizer
project_settings: Using found .deprc within:  /Users/mattwalters/development/electronifie/denormalizer/.deprc
project_settings: Using found .deprc within:  /Users/mattwalters/development/electronifie/denormalizer/.deprc
Setup Exception {'_filename': 'command_setup.py', 'message': "<class 'ValueError'>"}
error: Dependents

Setup was not successful. Please file an issue

For more info visit: https://github.com/mrjoelkemp/Dependents
JumpToDependency: region (51, 55)
JumpToDependency: line (32, 58)
JumpToDependency: strings on line ['llog']
JumpToDependency: regions [(51, 55)]
JumpToDependency: Extracted Path {'path': 'llog'}
Exception in thread Thread-11:
Traceback (most recent call last):
  File "./threading.py", line 901, in _bootstrap_inner
  File "/Users/mattwalters/Library/Application Support/Sublime Text 3/Packages/Dependents/JumpToDependency.py", line 54, in run
    if not self.window.config:
AttributeError: 'Window' object has no attribute 'config'
```

**Comment by mateodelnorte** [comment]
This is just an overall design comment, but I wonder if (instead of relying on a .deps file) you can instead search the current working file structure for known identifiers of different project types. For instance, you can do an initial indexing and look for any package.json files. When you find a package.json file you can instantiate an object that represents a node project and knows how to index files in its folder and under. Since node projects are always nested, you can create a tree of these and connect them together. This would make the approach automatically work for single of multi project scenarios. 

From there, you can add in different provider types, such as Python which would search for requirements.txt files or something like that. 

This may be similar to how webstorm and other JetBrains products work.

**Comment by mateodelnorte** [comment]
At that point, your code would auto-generate the config elements provided in your current .deps. But, you could also allow specification of .deps files in all those locations, in order to allow overriding defaults.

**Comment by mrjoelkemp** [comment]
Thanks for the insight @mateodelnorte. Having the tool work right out of the box is definitely a goal. 

Similar to your suggestion, I've thought about creating a background server to precompute the dependency trees and do iterative rebuilds of parts of the tree based on changes in the filesystem. This would yield very amazing performance gains for the various features of Dependents, at the cost of making sure the plugin cleans up the server appropriately on shutdown. This is similar to how http://ternjs.net/ works.

As a quicker fix to the configuration problem, I've thought about, post-install, presenting the user with a best guess at the configuration. The plugin would try to deduce the JS roots (using something like https://github.com/mrjoelkemp/node-app-root) and generate an initial `.deprc` file that the user could later customize/correct. Complementary to that is checking that the config paths point to real folders (#149) to give the user more insight into why the plugin isn't working.

Appreciate the insight.

**Comment by mrjoelkemp** [comment]
Hey @mateodelnorte. I pushed a bunch of fixes over the past couple of days. 

Specifically, in case your settings were incorrect, you'll now see a popup (as per #149) indicating which settings are invalid. 

In the console, I'm also outputting a better error message to help me track down what's going wrong.

Whenever you have time, if you wouldn't mind updating and then reporting back any errors. Thanks in advance!

**Comment by mrjoelkemp** [comment]
Closing until more info is provided. Happy to reopen if the issue persists.
