### ISSUE TITLE
Hitting error when installing tool

### ISSUE THREAD

**Issue by tnrich** [mrjoelkemp/Dependents#178]
Hey there,
I'm hitting some problems trying to use dependents and wasn't able to find an existing issue that addressed what I'm seeing.  Here's my setup:

```which node``` outputs /usr/local/bin/node

Here's my .deprc
```
{
    "root": "./",
  }
```
Which lives at the root of my commonjs-based codebase.

I installed through package control.

But when I try to run any of the dependents commands, nothing seems to happen.

Here's what's getting output to my sublime console:

```
find_base_path: Closest folder with a deprc: /Users/tnrich/Sites/webpackTrial
find_base_path: Closest folder with a deprc: /Users/tnrich/Sites/webpackTrial
project_settings: Using found .deprc within:  /Users/tnrich/Sites/webpackTrial/.deprc
command_setup: Expecting property name enclosed in double quotes: line 3 column 3 (char 22)
Probably no internet:  <class 'TypeError'>
Setup Exception {'message': ValueError('Expecting property name enclosed in double quotes: line 3 column 3 (char 22)',), '_filename': 'command_setup.py'}
BaseCommand: Setup was not successful
```

Any help would be appreciated. Thanks for your efforts!

**Comment by mrjoelkemp** [comment]
Thanks for reporting the issue and for checking out the tool. 

Seems like something might be off about your .deprc file: http://stackoverflow.com/a/15008158. Try recreating the file to see if that fixes the issue. 

What OS are you on by chance?

**Comment by tnrich** [comment]
Thanks for getting back to me. I'll try it out. I'm on OSX 10.10.4

**Comment by tnrich** [comment]
Whoops I realized it was a json issue with a trailing comma.

Seems to be getting futher but I'm now I'm running into a second set of issues when I try to "Open dependents":

```
Executing:  node /Users/tnrich/Library/Application Support/Sublime Text 3/Packages/Dependents/node_modules/dependents/bin/dependents.js --directory=/Users/tnrich/Sites/webpackTrial /Users/tnrich/Sites/webpackTrial/app/getReverseComplementSequenceString.js
Dependents: 2 dependents found:
/Users/tnrich/Sites/webpackTrial/app/getAminoAcidDataForEachBaseOfDna.js
/Users/tnrich/Sites/webpackTrial/app/getOrfsFromSequence.js
BaseThread: Opening: /app/getAminoAcidDataForEachBaseOfDna.js
Missing file {'filename': '/app/getAminoAcidDataForEachBaseOfDna.js', '_filename': 'BaseThread.py'}
error: Dependents

Can't find that file
BaseThread: Opening: /app/getOrfsFromSequence.js
Missing file {'filename': '/app/getOrfsFromSequence.js', '_filename': 'BaseThread.py'}
error: Dependents

Can't find that file
Run_Dependents {'modifier': 'OPEN_ALL', '_filename': 'BaseThread.py', 'etime': '5.1'}
```

I haven't looked into the issues here yet so I'll check them out and report back.

**Comment by tnrich** [comment]
Found this: #166 

But I'm not sure what I can change to get it to resolve properly. 

This is definitely a file:
/Users/tnrich/Sites/webpackTrial/app/getAminoAcidDataForEachBaseOfDna.js

But I'm not sure if 
Missing file {'filename': '/app/getAminoAcidDataForEachBaseOfDna.js'
that is the correct relative path..?

**Comment by mrjoelkemp** [comment]
Thanks for reporting back. I really appreciate your patience.

Looks like the root is being removed from the path when trying to open up
the file. I'll look into it as soon as i get a moment.

**Comment by mrjoelkemp** [comment]
Also, from your deprc (unless you added settings aside from the root),
you're not using a requirejs config (webpack config support is a planned
feature), so the issue that you found isn't relevant here. Thanks for
searching though!

**Comment by mrjoelkemp** [comment]
Quick follow-up: can you set your root to 'app'? If you could link me to a
sample repo, i could definitely track down the error.

**Comment by tnrich** [comment]
https://github.com/tnrich/webpackTrial

Here's the repo I was hoping to use it with. 

Setting the root to 'app' has it working now!

**Comment by tnrich** [comment]
Thanks for helping me solve this! Much appreciated! So does the "root" property refer to the file directory in which the "entry point" for your app lives?

**Comment by mrjoelkemp** [comment]
Great! It's really the javascript root; so yes, the root of all js files.

Thanks for the repo. I'll figure out how to avoid this confusion.

Enjoy!

**Comment by mrjoelkemp** [comment]
Closing since the issue was fixed. Opened https://github.com/mrjoelkemp/Dependents/issues/179 to handle showing the user when their deprc has invalid json.
