### ISSUE TITLE
Can we use the custom bindings (if supplied) and not the defaults?

### ISSUE THREAD

**Issue by mrjoelkemp** [mrjoelkemp/Dependents#26]
Folks want to change the bindings permanently, not add on additional ones.

**Comment by mrjoelkemp** [comment]
Second request for this. Basically, there are plugins that use that key binding. Folks shouldn't have to choose. If they supply a custom keybinding, that should be used instead of Dependents' defaults. 

This is possibly more of an issue of how Sublime Text handles keybinding configurations.

**Comment by tnrich** [comment]
Yeah, it would be great if users could set it so the Super+Alt+Right binding weren't overriding the ability to move one tab right. I use that one a lot.

**Comment by mrjoelkemp** [comment]
It's tough. There's a lot of value in having users download the plugin, press a few keys, and just get right to using the tool. The first version of dependents had users configure their keymap and mousemap; it was laborious. 

I don't see a way of avoiding key conflicts in general (across all plugins).

> Super+Alt+Right binding weren't overriding the ability to move one tab right

Is that on a Windows or Linux machine? I'm on osx and it's `Super + Shift + ]` to move one tab to the right.
